### ISSUE TITLE
failed to run the example on osx 

### ISSUE THREAD

**Issue by akhenakh** [orsinium-labs/wasm4go#2]
```
tinygo build -target ./target.json -gc     leaking -o      cart.wasm ./snake      
# runtime/interrupt
task: Failed to run task "run": exit status 1
```
tinygo version 0.31.0-dev-e19493b darwin/arm64 (using go version go1.22.0 and LLVM version 17.0.1)

Tested the amd64 version as well same error

**Comment by orsinium** [comment]
Hmmm 🤔 That's not much of information to guess the error and I don't have an OS X device to reproduce. Let's leave it open and see if anyone else faces the same issue.

Also, the TinyGo issue tracker might be a better place for this bug report. Wasm4go doesn't do anything special, it's just a Go library. The error either in TinyGo internals or in my `target.json` configuration. I suggest you try compiling something very simple, like an empty program with a single empty `main() {}`, using the provided `target.json` and if the problem persists open an issue in TinyGo repo.
