### ISSUE TITLE
failed to run the example on Linux

### ISSUE THREAD

**Issue by akhenakh** [orsinium-labs/wasm4go#3]
```
task: [build] test ./snake
task: [build] tinygo build -target ./target.json -gc     leaking -o      cart.wasm ./snake

wasm-ld: error: entry symbol not defined (pass --no-entry to suppress): _start
failed to run tool: wasm-ld
error: failed to link /tmp/tinygo617470736/main: exit status 1
task: Failed to run task "run": exit status 1
```

tinygo dev

tinygo version 0.31.0 linux/amd64 (using go version go1.22.0 and LLVM version 17.0.1)

**Comment by orsinium** [comment]
> tinygo version 0.31.0 linux/amd64

It's not a dev version. A dev build should include the word `dev` and the commit SHA in the version number. For example, this is what I have:

```
$ tinygo version  
tinygo version 0.31.0-dev-e9ca417 linux/amd64 (using go version go1.21.3 and LLVM version 17.0.1)
```

Try removing the old tinygo `sudo rm $(which tinygo)` and installing the dev build again.

**Comment by orsinium** [comment]
I found the issue. See #4.
